name: Tests

on: [pull_request, push]

env:
  DECOMPILER_VERSION: "10.0"
permissions:
  contents: read

jobs:
  recomp_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv and set the python version
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        uv sync --group dev
    - name: Cache decompiler
      id: cache-decompiler
      uses: actions/cache@v3
      with:
        path: ./Decompiler
        key: ${{ runner.os }}-test-decompiler-${{ env.DECOMPILER_VERSION }}
    - if: ${{ steps.cache-decompiler.outputs.cache-hit != 'true' }}
      name: Download decompiler
      uses: robinraju/release-downloader@v1.12
      with:
        repository: 'ValveResourceFormat/ValveResourceFormat'
        tag: ${{ env.DECOMPILER_VERSION }}
        fileName: 'Decompiler-linux-x64.zip'
        zipBall: true
        extract: true
        token: ${{ secrets.GH_TOKEN }}
    - name: Run test
      run: |
        export PYTHONPATH=$(pwd)
        chmod +x ./Decompiler
        uv run pytest
